---
resources:
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: cf-mysql-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cf-mysql-ci.git
    branch: master

- name: cf-mysql-deployment-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-mysql-deployment.git
    branch: master
    private_key: {{git-writer-private-key}}

- name: cf-mysql-deployment-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-mysql-deployment.git
    branch: develop
    private_key: {{git-writer-private-key}}

- name: aws-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: cf-mysql-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release

jobs:
- name: update-releases
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-mysql-ci
    - get: runtime-ci
    - get: cf-mysql-deployment-develop
    - get: cf-mysql-deployment-master
    - get: stemcell
      resource: aws-bosh-stemcell
      params:
        tarball: false
    - get: cf-mysql-release
      params:
        tarball: false
  - task: create-binaries-manifest-section
    file: cf-mysql-ci/ci/tasks/create-binaries-manifest-section.yml
    input_mapping:
      deployment-configuration: cf-mysql-deployment-develop
    output_mapping:
      deployment-manifest: deployment-manifest
  - task: commit-generated-manifest
    file: cf-mysql-ci/ci/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-mysql-deployment-master
      manifest: deployment-manifest
    output_mapping:
      updated-repo: updated-repo
    params:
      MANIFEST_NAME: cf-mysql-deployment.yml
      MANIFEST_DESTINATION: cf-mysql-deployment.yml
  - put: cf-mysql-deployment-master
    params:
      repository: updated-repo
