---
resources:
- name: cf-mysql-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-mysql-release.git
    branch: develop
    private_key: {{git-writer-private-key}}

- name: cf-mysql-release-candidate
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-mysql-release.git
    branch: release-candidate
    private_key: {{git-writer-private-key}}

- name: cf-mysql-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-mysql-release.git
    branch: master
    private_key: {{git-writer-private-key}}

- name: cf-mysql-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cf-mysql-ci.git
    private_key: {{git-writer-private-key}}

- name: deployments-core-services
  type: git
  source:
    uri: git@github.com:pivotal-cf/deployments-core-services
    private_key: {{git-writer-private-key}}

- name: s3-resource-final-release
  type: s3
  source:
    bucket: cf-mysql-releases
    access_key_id: {{cf-mysql-ci-aws-access-key-id}}
    secret_access_key: {{cf-mysql-ci-aws-secret-access-key}}

- name: release-notes
  type: s3
  source:
    bucket: cf-mysql-release-notes
    regexp: RELEASE_NOTES_v(\d+)
    access_key_id: {{cf-mysql-ci-aws-access-key-id}}
    secret_access_key: {{cf-mysql-ci-aws-secret-access-key}}

- name: publish-github-release
  type: github-release
  source:
    user: cloudfoundry
    repository: cf-mysql-release
    access_token: {{git-writer-github-access-token}}

jobs:
  - name: final-release
    plan:
      - aggregate:
        - get: cf-mysql-master
          params:
            fetch:
            - develop
            - release-candidate
        - get: cf-mysql-ci
        - get: deployments-core-services
        - get: cf-mysql-develop
        - get: release-notes
          trigger: true
      - task: final-release
        config:
          platform: linux
          image: docker:///cloudfoundry/cf-mysql-ci
          inputs:
          - name: cf-mysql-ci
          - name: cf-mysql-master
            path: cf-mysql-release
          - name: release-notes
          run:
            path: cf-mysql-ci/scripts/publish/cut-final-release
          params:
            RELEASE_NOTES_DIRECTORY: release-notes
            OUTPUT_RELEASE_ARTIFACTS: output-release-dir/release-artifacts
            OUTPUT_RELEASE_TAG: output-release-dir/cf-mysql-tag
            OUTPUT_RELEASE_NOTES: output-release-dir/generated-release-notes
            OUTPUT_RELEASE_COMMIT: output-release-dir/git-commit
            RELEASE_ACCESS_KEY: {{cf-mysql-publish-blobs-aws-access-key-id}}
            RELEASE_SECRET_KEY: {{cf-mysql-publish-blobs-aws-secret-access-key}}
          outputs:
            - name: output-release-dir
      - task: merge-master-into-develop
        config:
          platform: linux
          image: docker:///cloudfoundry/cf-mysql-ci
          inputs:
          - name: cf-mysql-ci
          - name: cf-mysql-develop
          run:
            path: cf-mysql-ci/scripts/publish/merge-master-into-develop
      - put: publish-github-release
        params:
          name: output-release-dir/cf-mysql-tag
          tag: output-release-dir/cf-mysql-tag
          body: output-release-dir/generated-release-notes
          commitish: output-release-dir/git-commit
          globs:
          - output-release-dir/release-artifacts/*.tgz
      - put: cf-mysql-ci
        params:
          repository: cf-mysql-ci
          tag: output-release-dir/cf-mysql-tag
          only_tag: true
          tag_prefix: cf-mysql-
      - put: deployments-core-services
        params:
          repository: deployments-core-services
          tag: output-release-dir/cf-mysql-tag
          only_tag: true
          tag_prefix: cf-mysql-
      - put: s3-resource-final-release
        params:
          from: output-release-dir\/release-artifacts\/.*\.tgz
          to: final/

groups: [{name: cf-mysql-final, jobs: [final-release]}]
