---
#
# Deploy the cf-mysql release candidate to the "sriracha" environment.
# Triggered by updates to the release-candidate branch.
#

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: gcp-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: cf-mysql-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cf-mysql-ci.git

- name: deployments-configuration
  type: git
  source:
    uri: git@github.com:pivotal-cf/deployments-core-services
    private_key: {{git-private-key}}

- name: cf-mysql-release-rc
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-mysql-release
    branch: release-candidate
    private_key: {{git-writer-private-key}}

- name: cf-mysql-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-mysql-deployment.git
    branch: develop
    private_key: {{git-writer-private-key}}

- name: cf-mysql-rc-bucket
  type: s3
  source:
    bucket: cf-mysql-releases
    regexp: release-candidate/cf-mysql-(.*-rc.*)\.tgz
    access_key_id: {{cf-mysql-ci-aws-access-key-id}}
    secret_access_key: {{cf-mysql-ci-aws-secret-access-key}}

- name: full-bosh-acceptance-environment
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/core-services-oss-env-resource-pool
    branch: master
    pool: full-bosh-acceptance
    private_key: {{git-writer-private-key}}

- name: compiled-packages-lock
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/core-services-oss-env-resource-pool
    branch: master
    pool: compiled-packages
    private_key: {{git-writer-private-key}}

- name: acceptance-deployment
  type: bosh-deployment
  source:
    deployment: cf-mysql

- name: routing-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-routing-release

jobs:
- name: claim-full-bosh-environment
  plan:
  - aggregate:
    - get: cf-mysql-release
      resource: cf-mysql-release-rc
      trigger: true
    - put: full-bosh-acceptance-environment
      params:
        acquire: true

- name: delete-acceptance-deployment
  plan:
  - do:
    - timeout: 1h
      aggregate:
      - get: full-bosh-acceptance-environment
        passed: [claim-full-bosh-environment]
        trigger: true
        version: every
      - get: cf-mysql-release
        resource: cf-mysql-release-rc
        passed: [claim-full-bosh-environment]
      - get: cf-mysql-ci
      - get: deployments-configuration
    - try:
        task: run-deregister-and-purge-instances
        config:
          platform: linux
          image_resource: &image_resource
            type: docker-image
            source:
              repository: cloudfoundry/cf-mysql-ci
          inputs:
            - name: cf-mysql-ci
            - name: deployments-configuration
            - name: full-bosh-acceptance-environment
          params:
            ENV_REPO: deployments-configuration
            ENV_TARGET_FILE: full-bosh-acceptance-environment/name
            ENV_METADATA: full-bosh-acceptance-environment/metadata
            ERRAND: deregister-and-purge-instances
            SKIP_IF_NO_DEPLOYMENT: true
            BOSH_DEPLOYMENT: cf-mysql
          run:
            path: cf-mysql-ci/scripts/bosh/run_errand_gcp
    - task: delete-acceptance-deployment
      config:
        platform: linux
        image_resource: *image_resource
        inputs:
          - name: cf-mysql-ci
          - name: deployments-configuration
          - name: full-bosh-acceptance-environment
        params:
          ENV_REPO: deployments-configuration
          ENV_TARGET_FILE: full-bosh-acceptance-environment/name
          ENV_METADATA: full-bosh-acceptance-environment/metadata
          BOSH_DEPLOYMENT: cf-mysql
        run:
          path: cf-mysql-ci/scripts/bosh/delete_deployment_gcp

- name: deploy-to-acceptance
  plan:
  - do:
    - timeout: 5h
      aggregate:
      - get: cf-mysql-ci
      - get: deployments-configuration
      - get: cf-mysql-release
        resource: cf-mysql-release-rc
        passed: [delete-acceptance-deployment]
      - get: cf-mysql-deployment
      - get: gcp-bosh-stemcell
      - get: full-bosh-acceptance-environment
        passed: [delete-acceptance-deployment]
        trigger: true
        version: every
      - get: release-tarball
        resource: cf-mysql-rc-bucket
      - get: routing-release
    - task: make-manifest
      config:
        platform: linux
        image_resource: *image_resource
        inputs:
        - name: cf-mysql-ci
        - name: cf-mysql-deployment
        - name: deployments-configuration
        - name: cf-mysql-release
        - name: full-bosh-acceptance-environment
        outputs:
        - name: deployment-manifest
        params:
          ENV_NAME_FILE: full-bosh-acceptance-environment/name
          ENV_METADATA: full-bosh-acceptance-environment/metadata
          DEPLOYMENTS_DIR: deployments-configuration
        run:
          path: cf-mysql-ci/scripts/bosh/make-manifest-gobosh-gcp
    - put: compiled-packages-lock
      params:
        acquire: true
    - task: compile-release
      config:
        platform: linux
        image_resource: *image_resource
        inputs:
        - name: cf-mysql-ci
        - name: gcp-bosh-stemcell
        - name: release-tarball
        outputs:
        - name: compiled-release-tarball
        params:
          BOSH_CLIENT: ((concourse-compilation-director/Notes/BOSH_CLIENT))
          BOSH_CLIENT_SECRET: ((concourse-compilation-director/Notes/BOSH_CLIENT_SECRET))
          BOSH_ENVIRONMENT: ((concourse-compilation-director/Notes/BOSH_ENVIRONMENT))
          BOSH_CA_CERT: ((concourse-compilation-director/Notes/BOSH_CA_CERT))
        run:
          path: cf-mysql-ci/scripts/compile_release
      ensure:
        put: compiled-packages-lock
        params:
          release: compiled-packages-lock
    - put: acceptance-deployment
      params:
        source_file: full-bosh-acceptance-environment/metadata
        manifest: deployment-manifest/deployment.yml
        releases:
        - compiled-release-tarball/*.tgz
        - routing-release/*.tgz
        stemcells: [gcp-bosh-stemcell/*.tgz]

- name: run-smoke-tests-acceptance
  plan:
  - do:
    - timeout: 3h
      aggregate:
      - get: full-bosh-acceptance-environment
        passed: [deploy-to-acceptance]
        trigger: true
        version: every
      - get: cf-mysql-release
        resource: cf-mysql-release-rc
        passed: [deploy-to-acceptance]
      - get: cf-mysql-ci
      - get: deployments-configuration
    - task: run-broker-registrar
      config:
        platform: linux
        image_resource: *image_resource
        inputs:
          - name: cf-mysql-ci
          - name: deployments-configuration
          - name: full-bosh-acceptance-environment
        params:
          ENV_REPO: deployments-configuration
          ENV_TARGET_FILE: full-bosh-acceptance-environment/name
          ENV_METADATA: full-bosh-acceptance-environment/metadata
          ERRAND: broker-registrar
          BOSH_DEPLOYMENT: cf-mysql
        run:
          path: cf-mysql-ci/scripts/bosh/run_errand_gcp
    - task: run-smoke-tests
      config:
        platform: linux
        image_resource: *image_resource
        inputs:
          - name: cf-mysql-ci
          - name: deployments-configuration
          - name: full-bosh-acceptance-environment
        params:
          ENV_REPO: deployments-configuration
          ENV_TARGET_FILE: full-bosh-acceptance-environment/name
          ENV_METADATA: full-bosh-acceptance-environment/metadata
          ERRAND: smoke-tests
          BOSH_DEPLOYMENT: cf-mysql
        run:
          path: cf-mysql-ci/scripts/bosh/run_errand_gcp

- name: release-acceptance-environment
  plan:
  - aggregate:
    - get: cf-mysql-release
      resource: cf-mysql-release-rc
      passed: [run-smoke-tests-acceptance]
    - get: full-bosh-acceptance-environment
      passed: [run-smoke-tests-acceptance]
      trigger: true
      version: every
  - put: full-bosh-acceptance-environment
    params:
      release: full-bosh-acceptance-environment
