---
resources:
- name: acceptance-env-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: cf-mysql-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cf-mysql-ci.git

- name: deployments-configuration
  type: git
  source:
    uri: git@github.com:pivotal-cf/deployments-core-services
    private_key: {{git-private-key}}

- name: cf-mysql-release-rc
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-mysql-release
    branch: release-candidate
    private_key: {{git-writer-private-key}}

- name: aws-acceptance-environment
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/core-services-oss-env-resource-pool
    branch: master
    pool: aws-acceptance
    private_key: {{git-writer-private-key}}

- name: acceptance-deployment
  type: bosh-deployment
  source:
    target: https://bosh.primo.cf-app.com:25555
    username: {{acceptance_env_bosh_username}}
    password: {{acceptance_env_bosh_password}}
    deployment: cf-primo-mysql
    ignore_ssl: true

jobs:
- name: claim-aws-environment
  plan:
  - aggregate:
    - get: cf-mysql-release
      resource: cf-mysql-release-rc
      trigger: true
    - put: aws-acceptance-environment
      params:
        acquire: true

- name: delete-acceptance-deployment
  plan:
  - aggregate:
    - get: aws-acceptance-environment
      passed: [claim-aws-environment]
    - get: cf-mysql-release
      resource: cf-mysql-release-rc
      passed: [claim-aws-environment]
      trigger: true
    - get: cf-mysql-ci
    - get: deployments-configuration
  - task: run-broker-deregistrar
    config:
      platform: linux
      image: docker:///cloudfoundry/cf-mysql-ci
      inputs:
        - name: cf-mysql-ci
        - name: deployments-configuration
      params:
        ENV: primo
        DEPLOYMENT_NAME: cf-primo-mysql
        BOSH_USER: {{acceptance_env_bosh_username}}
        BOSH_PASSWORD: {{acceptance_env_bosh_password}}
        ERRAND: broker-deregistrar
        SKIP_IF_NO_DEPLOYMENT: true
      run:
        path: cf-mysql-ci/scripts/bosh/run_errand
  - task: delete-acceptance-deployment
    config:
      platform: linux
      image: docker:///cloudfoundry/cf-mysql-ci
      inputs:
        - name: cf-mysql-ci
        - name: deployments-configuration
      params:
        ENV: primo
        DEPLOYMENT_NAME: cf-primo-mysql
        BOSH_USER: {{acceptance_env_bosh_username}}
        BOSH_PASSWORD: {{acceptance_env_bosh_password}}
      run:
        path: cf-mysql-ci/scripts/bosh/delete_deployment

- name: deploy-to-acceptance
  plan:
  - aggregate:
    - get: cf-mysql-ci
    - get: deployments-configuration
    - get: cf-mysql-release
      resource: cf-mysql-release-rc
      passed: [delete-acceptance-deployment]
      trigger: true
    - get: acceptance-env-bosh-stemcell
    - get: aws-acceptance-environment
      passed: [delete-acceptance-deployment]
  - aggregate:
    - task: create-release
      config:
        platform: linux
        image: docker:///cloudfoundry/cf-mysql-ci
        inputs:
        - name: cf-mysql-ci
        - name: cf-mysql-release
        params:
          RELEASE_RELATIVE_DIR: cf-mysql-release/
          BOSH_USER: {{acceptance_env_bosh_username}}
          BOSH_PASSWORD: {{acceptance_env_bosh_password}}
        run:
          path: cf-mysql-ci/scripts/create_release
    - task: make-manifest
      config:
        platform: linux
        image: docker:///cloudfoundry/cf-mysql-ci
        inputs:
        - name: cf-mysql-ci
        - name: deployments-configuration
        - name: cf-mysql-release
        params:
          ENV: primo
          BOSH_USER: {{acceptance_env_bosh_username}}
          BOSH_PASSWORD: {{acceptance_env_bosh_password}}
          DEPLOYMENTS_DIR: deployments-configuration
        run:
          path: cf-mysql-ci/scripts/bosh/make_manifest
  - put: acceptance-deployment
    params:
      manifest: make-manifest/cf-mysql-release/deployment.yml
      releases: [create-release/cf-mysql-release/dev_releases/cf-mysql/*.tgz]
      stemcells: [acceptance-env-bosh-stemcell/*.tgz]

- name: run-smoke-tests-acceptance
  plan:
  - aggregate:
    - get: aws-acceptance-environment
      passed: [deploy-to-acceptance]
    - get: cf-mysql-release
      resource: cf-mysql-release-rc
      passed: [deploy-to-acceptance]
      trigger: true
    - get: cf-mysql-ci
    - get: deployments-configuration
  - task: run-broker-registrar
    config:
      platform: linux
      image: docker:///cloudfoundry/cf-mysql-ci
      inputs:
        - name: cf-mysql-ci
        - name: deployments-configuration
      params:
        ENV: primo
        DEPLOYMENT_NAME: cf-primo-mysql
        BOSH_USER: {{acceptance_env_bosh_username}}
        BOSH_PASSWORD: {{acceptance_env_bosh_password}}
        ERRAND: broker-registrar
      run:
        path: cf-mysql-ci/scripts/bosh/run_errand
  - task: run-smoke-tests
    config:
      platform: linux
      image: docker:///cloudfoundry/cf-mysql-ci
      inputs:
        - name: cf-mysql-ci
        - name: deployments-configuration
      params:
        ENV: primo
        DEPLOYMENT_NAME: cf-primo-mysql
        BOSH_USER: {{acceptance_env_bosh_username}}
        BOSH_PASSWORD: {{acceptance_env_bosh_password}}
        ERRAND: acceptance-tests
      run:
        path: cf-mysql-ci/scripts/bosh/run_errand

- name: release-acceptance-environment
  plan:
  - aggregate:
    - get: cf-mysql-release
      resource: cf-mysql-release-rc
      passed: [run-smoke-tests-acceptance]
      trigger: true
    - get: aws-acceptance-environment
      passed: [run-smoke-tests-acceptance]
  - put: aws-acceptance-environment
    params:
      release: aws-acceptance-environment
