---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: deployments

outputs:
- name: deployments-terraformed

run:
  path: cf-mysql-ci/ci/tasks/bosh-lite-gcp/apply-terraform.sh

params:
  OUTPUT_DIR: deployments-terraformed
  DEPLOYMENTS_DIR: deployments
