---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: release-tarball

outputs:
- name: release-override

params:
  OUTPUT_DIR: release-override
  RELEASE_TARBALL_DIR: release-tarball

run:
  path: cf-mysql-ci/scripts/create_release_override

