---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cf-mysql-ci}

inputs:
- name: cf-mysql-ci
- name: release-repo
- name: version

outputs:
- name: commit-message
- name: release-tarball
- name: release-repo-modified

params:
  RELEASE_NAME: ~
  BLOBS_BUCKET_NAME: ~
  AWS_ACCESS_KEY_ID: ~
  AWS_SECRET_ACCESS_KEY: ~
  FINAL: ~
  SHA2: ~
  BOSH_SHA2: false

run:
  path: cf-mysql-ci/scripts/create_release
