---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cf-mysql-ci}

inputs:
- name: cf-mysql-ci
- name: release-repo
- name: version

outputs:
- name: release-tarball

params:
  RELEASE_NAME: ~

run:
  path: cf-mysql-ci/scripts/create_release
