---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: bosh-lite-environment

run:
  path: cf-mysql-ci/scripts/bosh/delete_deployment_gcp

params:
  ENV_METADATA: bosh-lite-environment/metadata
  BOSH_DEPLOYMENT: ~
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
  BOSH_ENVIRONMENT:

