---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: environment

run:
  path: cf-mysql-ci/scripts/bosh/delete_deployment_gcp

params:
  ENV_METADATA: environment/metadata
  BOSH_DEPLOYMENT: ~
