---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: deployments

run:
  path: cf-mysql-ci/scripts/bosh-lite-gcp/destroy-terraform

params:
  DEPLOYMENTS_DIR: deployments
