---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: cf-deployment

outputs:
- name: cloud-config

run:
  path: cf-mysql-ci/scripts/bosh-lite-gcp/generate-cloud-config
