---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: cf-mysql-release

outputs:
  - name: deployment-manifest

run:
  path: cf-mysql-ci/scripts/bosh-lite/make-manifest-ondemand

params:
  OUTPUT_FILE: deployment-manifest/deployment.yml
  DISABLE_INTERRUPTOR: false