---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: cf-mysql-deployment
- name: bosh-lite-environment

outputs:
- name: deployment-manifest

run:
  path: cf-mysql-ci/scripts/bosh-lite/make-manifest-gobosh-pooled

params:
  OUTPUT_FILE: deployment-manifest/deployment.yml
  DISABLE_INTERRUPTOR: false
  MINIMAL_MODE: false
  NO_ARBITRATOR: false
