---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: cf-deployment
- name: url

outputs:
- name: cf-deployment-manifest

run:
  path: cf-mysql-ci/scripts/bosh-lite/make-cf-manifest-ondemand

params:
  OUTPUT_FILE: deployment-manifest/cf.yml
  DNS_NAME: url/url
