platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalcf/mysql-restore
inputs:
- name: cf-mysql-release
run:
  path: cf-mysql-release/src/quota-enforcer/bin/test-integration
