---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: cf-deployment


run:
  path: sh
  args:
  - |
    BOSH_ENVIRONMENT="$(cat "${ENV_TARGET_FILE}")" \
    bosh2 -n update-cloud-config "${cf-deployment}/bosh-lite/cloud-config.yml"
