---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: a1-env
- name: gcp-bosh-stemcell

run:
  path: cf-mysql-ci/scripts/bosh/upload-a1-stemcell
