---
- type: replace
  path: /vm_extensions/-
  value:
    name: p-mysql-broker-lb
    cloud_properties:
      ports:
      - host: 443

- type: replace
  path: /vm_extensions/-
  value:
    name: p-mysql-proxy-lb
    cloud_properties:
      ports:
      - host: 8080 # is this necessary?
      - host: 3306

- type: replace
  path: /vm_types/-
  value:
    name: default
