---
- type: replace
  path: /vm_extensions/-
  value:
    name: mysql-broker-lb
    cloud_properties:
      ports:
      - host: 443

- type: replace
  path: /vm_extensions/-
  value:
    name: mysql-proxy-lb
    cloud_properties:
      ports:
      - host: 8080
      - host: 3306

- type: replace
  path: /vm_types/name=default?
  value:
    name: default
