platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalcf/mysql-restore
inputs:
- name: bosh-lite-environment
- name: cf-mysql-ci
params:
  ENV_TARGET_FILE: bosh-lite-environment/name
  BOSH_LITE_SSH_KEY:
run:
  path: cf-mysql-ci/scripts/persistence/load-test-data
